EXPERIMENT_INFRA_SUBDIRECTORY_NAME = "infra"
EXPERIMENT_SCHEDULE_SUBDIRECTORY_NAME = "schedule"
EXPERIMENT_DATA_SUBDIRECTORY_NAME = "data"
EXPERIMENT_ANALYSIS_SUBDIRECTORY_NAME = "analysis"

# CAVEAT: no final slash! (basename of path with final slash is empty)
INFRAS_AND_SCHEDULES_FOLDER = "NEW_YEAR_TEST"
BASELINE_DATA_FOLDER = "../rsp-data/PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/"
BASELINE_DATA_FOLDER = "../rsp-data/PUBLICATION_DATA/NEW_RUN_END_OF_YEAR/"
