apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  host: "{{ .Release.Name }}.app.gpu.otc.sbb.ch"
  port:
    targetPort: 8888
  tls:
    termination: edge
  to:
    kind: Service
    name:  {{ .Release.Name }}
    weight: 100
  wildcardPolicy: None
{{ include "chart.helmRouteFix" $ }}
