"""Tools and Methods to analyse the data generated by the experiments.

Methods
-------
average_over_trials
    Average over all the experiment trials
"""
import os
from typing import List
from typing import Optional
from typing import Tuple

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import axes
from mpl_toolkits.mplot3d import Axes3D
from pandas import DataFrame

matplotlib.use('Qt5Agg')
# Dummy import currently because otherwise the import is removed all the time but used by 3d scatter plot
axes3d = Axes3D


# https://stackoverflow.com/questions/25649429/how-to-swap-two-dataframe-columns
def swap_columns(df: DataFrame, c1: int, c2: int):
    """Swap columns in a data frame.

    Parameters
    ----------
    df: DataFrame
        The data frame.
    c1: int
        the column index
    c2: int
        the other column index.
    """
    df['temp'] = df[c1]
    df[c1] = df[c2]
    df[c2] = df['temp']
    df.drop(columns=['temp'], inplace=True)


def average_over_trials(experimental_data: DataFrame) -> Tuple[DataFrame, DataFrame]:
    """
    Average over all the experiment trials
    Parameters
    ----------
    experimental_data

    Returns
    -------
    DataFrame of mean data and DataFram of standard deviations
    """

    averaged_data = experimental_data.groupby(['experiment_id']).mean().reset_index()
    standard_deviation_data = experimental_data.groupby(['experiment_id']).std().reset_index()
    return averaged_data, standard_deviation_data


def three_dimensional_scatter_plot(data: DataFrame,
                                   columns: DataFrame.columns,
                                   error: DataFrame = None,
                                   file_name: str = "",
                                   fig: Optional[matplotlib.figure.Figure] = None,
                                   subplot_pos: str = '111',
                                   subplot_title: str = '',
                                   colors: Optional[List[str]] = None):
    """Adds a 3d-scatterplot as a subplot to a figure.

    Parameters
    ----------
    data: DataFrame
        DataFrame containing data to be plotted
    error: DataFrame
        DataFrame containing error of z values to plot
    columns: DataFrame.columns
        Three columns of that data frame to be plotted against each other, x_values, y_values,z_values
    file_name: string
        If provided the plot is stored to figure instead of shown
    fig: Optional[matplotlib.figure.Figure]
        If given, adds the subplot to this figure without showing it, else creates a new one and shows it.
    subplot_pos: str
        a 3-digit integer describing the position of the subplot.
    colors: List[str]
        List of colors for the data points.

    Returns
    -------
    """
    x_values = data[columns[0]].values
    y_values = data[columns[1]].values
    z_values = data[columns[2]].values
    experiment_ids = data['experiment_id'].values

    show = False
    if fig is None:
        show = True
        fig = plt.figure()

    ax: axes.Axes = fig.add_subplot(subplot_pos, projection='3d')
    ax.set_xlabel(columns[0])
    ax.set_ylabel(columns[1])
    ax.set_zlabel(columns[2])
    if not subplot_title:
        ax.set_title(str(columns))
    else:
        ax.set_title(subplot_title)

    ax.scatter(x_values, y_values, z_values, color=colors)
    for i in np.arange(0, len(z_values)):
        ax.text(x_values[i], y_values[i], z_values[i], "{}".format(experiment_ids[i]))

    if error is not None:
        # plot errorbars
        z_error = error[columns[2]].values
        for i in np.arange(0, len(z_values)):
            ax.plot([x_values[i], x_values[i]], [y_values[i], y_values[i]],
                    [z_values[i] + z_error[i], z_values[i] - z_error[i]], marker="_")

    if len(file_name) > 1:
        plt.savefig(file_name)
    elif show:
        plt.show()


def two_dimensional_scatter_plot(data: DataFrame,
                                 columns: DataFrame.columns,
                                 error: DataFrame = None,
                                 baseline: DataFrame = None,
                                 link_column: str = 'size',
                                 file_name: Optional[str] = None,
                                 output_folder: Optional[str] = None,
                                 fig: Optional[matplotlib.figure.Figure] = None,
                                 subplot_pos: str = '111',
                                 title: str = None,
                                 colors: Optional[List[str]] = None,
                                 xscale: Optional[str] = None,
                                 yscale: Optional[str] = None
                                 ):
    """Adds a 2d-scatterplot as a subplot to a figure.

    Parameters
    ----------
    data: DataFrame
        DataFrame containing data to be plotted
    error: DataFrame
        DataFrame containing error of z values to plot
    columns: DataFrame.columns
        Three columns of that data frame to be plotted against each other, x_values, y_values,z_values
    file_name: string
        If provided the plot is stored to figure instead of shown
    fig: Optional[matplotlib.figure.Figure]
        If given, adds the subplot to this figure without showing it, else creates a new one and shows it.
    subplot_pos: str
        a 3-digit integer describing the position of the subplot.
    colors: List[str]
        List of colors for the data points.
    link_column
        Group data points by this column and draw a bar between consecutive data points.
    baseline
        data points that define a baseline. Visualized by a bar
    output_folder
        Save plot to this folder.
    title
        Plot title
    xscale
        Passed to matplotlib. See there for possible values such as 'log'.
    yscale
        Passed to matplotlib. See there for possible values such as 'log'.

    Returns
    -------
    """
    x_values = data[columns[0]].values
    y_values = data[columns[1]].values
    experiment_ids = data['experiment_id'].values

    if fig is None:
        fig = plt.figure()
        fig.set_size_inches(w=15, h=15)

    ax: axes.Axes = fig.add_subplot(subplot_pos)
    if title:
        ax.set_title(title)
    ax.set_xlabel(columns[0])
    ax.set_ylabel(columns[1])
    if xscale:
        ax.set_xscale(xscale)
    if yscale:
        ax.set_yscale(yscale)

    ax.scatter(x_values, y_values, color=colors)
    _2d_plot_label_scatterpoints(ax, experiment_ids, x_values, y_values)
    if error is not None:
        _2d_plot_errorbars(ax, columns, error, x_values, y_values)
    if baseline is not None:
        _2d_plot_baseline(ax, baseline, x_values, y_values)

    if link_column is not None:
        _2d_plot_link_column(ax, columns, data, link_column)

    if file_name is not None:
        plt.savefig(file_name)
    elif output_folder is not None:
        plt.savefig(os.path.join(output_folder, 'experiment_agenda_analysis_' + '_'.join(columns) + '.png'))


def _2d_plot_label_scatterpoints(ax, experiment_ids, x_values, y_values):
    for i in np.arange(0, len(y_values)):
        ax.text(x_values[i], y_values[i], "{}".format(experiment_ids[i]))


def _2d_plot_link_column(ax, columns, data, link_column):
    grouped_data = data.groupby([link_column])
    for _, group in grouped_data:
        sorted_group = group.sort_values(columns[0])
        # index is experiment_id! Therefore, count the number of iterations
        count = 0
        for index, _ in sorted_group.iterrows():
            if count == len(sorted_group) - 2:
                break
            count += 1
            ax.plot([sorted_group.at[index, columns[0]], sorted_group.at[index + 1, columns[0]]],
                    [sorted_group.at[index, columns[1]], sorted_group.at[index + 1, columns[1]]],
                    marker="_",
                    color='black')


def _2d_plot_errorbars(ax, columns, error, x_values, y_values):
    y_error = error[columns[1]].values
    for i in np.arange(0, len(y_values)):
        ax.plot([x_values[i], x_values[i]],
                [y_values[i] + y_error[i], y_values[i] - y_error[i]], marker="_")


def _2d_plot_baseline(ax, baseline, x_values, y_values):
    for i in np.arange(0, len(y_values)):
        ax.plot([x_values[i], x_values[i]],
                [baseline[i], y_values[i]], marker="_")
