---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
# %autosave 0
# %load_ext autoreload
# %autoreload 2
import sys
sys.path.append("../../src/python")
sys.path.append("../../src/asp")
from IPython.display import Video
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff


from rsp.step_03_run.experiments import *
from rsp.step_04_analysis.detailed_experiment_analysis.detailed_experiment_analysis import *
from rsp.step_04_analysis.detailed_experiment_analysis.resources_plotting_information import *
from rsp.step_04_analysis.detailed_experiment_analysis.flatland_rendering import *
from rsp.step_04_analysis.detailed_experiment_analysis.scatter_with_slider import *
from rsp.step_04_analysis.detailed_experiment_analysis.time_resource_plots_from_data_frames import *


from rsp.step_04_analysis.plot_utils import *
from rsp.utils.global_data_configuration import *
from rsp.utils.resource_occupation import *
from rsp.scheduling.asp.asp_helper import _print_stats

import pprint

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

_pp = pprint.PrettyPrinter(indent=4)

INFRAS_AND_SCHEDULES_FOLDER = f"../../{INFRAS_AND_SCHEDULES_FOLDER}"
BASELINE_DATA_FOLDER = f"../../{BASELINE_DATA_FOLDER}"

# if we have csv_only=True, re-run the experiment to generate pkl as well?
run_experiment = False
```

```{python}
experiment_base_directory = BASELINE_DATA_FOLDER

experiment_of_interest = 342
```

```{python}
if run_experiment:
        run_experiment_agenda(
            experiment_base_directory=INFRAS_AND_SCHEDULES_FOLDER,
            experiment_output_directory=BASELINE_DATA_FOLDER,
            csv_only=False,
            filter_experiment_agenda=lambda experiment_parameters: experiment_parameters.experiment_id == experiment_of_interest,
        )
```

```{python}
experiment_data_directory = f'{experiment_base_directory}/{EXPERIMENT_DATA_SUBDIRECTORY_NAME}'

experiment_results_list, experiment_results_analysis_list = load_and_expand_experiment_results_from_data_folder(
    experiment_data_folder_name=experiment_data_directory,
    experiment_ids=[experiment_of_interest],
)
exp_results_of_experiment_of_interest: ExperimentResults = experiment_results_list[0]
exp_results_analysis_of_experiment_of_interest: ExperimentResultsAnalysis = experiment_results_analysis_list[0]
agent_of_interest = exp_results_of_experiment_of_interest.experiment_parameters.re_schedule_parameters.malfunction_agent_id

malfunction  = gen_malfunction(
        earliest_malfunction=exp_results_of_experiment_of_interest.experiment_parameters.re_schedule_parameters.earliest_malfunction,
        malfunction_duration=exp_results_of_experiment_of_interest.experiment_parameters.re_schedule_parameters.malfunction_duration,
        malfunction_agent_id=exp_results_of_experiment_of_interest.experiment_parameters.re_schedule_parameters.malfunction_agent_id,
        schedule_trainruns=exp_results_of_experiment_of_interest.results_schedule.trainruns_dict,
    )
print(malfunction)
```

```{python}
experiment_agenda = load_experiment_agenda_from_file(experiment_base_directory)
```

```{python}
resource_occupations_for_all_scopes = extract_resource_occupations_for_all_scopes(experiment_result=exp_results_of_experiment_of_interest)
plotting_information: PlottingInformation = extract_plotting_information(
    schedule_as_resource_occupations=resource_occupations_for_all_scopes.schedule,
    grid_depth=exp_results_of_experiment_of_interest.experiment_parameters.infra_parameters.width,
    sorting_agent_id=agent_of_interest
)
```

```{python}
print(f"agent_of_interest={agent_of_interest}")
```

```{python}
full_df, df_background, sorted_resource_occupations_per_scope_and_agent = extract_full_df_from_experiment_results(
    exp_results_of_experiment_of_interest=exp_results_of_experiment_of_interest,
    global_constants=experiment_agenda.global_constants
)
```

```{python}
height = exp_results_of_experiment_of_interest.experiment_parameters.infra_parameters.height
width = exp_results_of_experiment_of_interest.experiment_parameters.infra_parameters.width
num_agents = exp_results_of_experiment_of_interest.experiment_parameters.infra_parameters.number_of_agents
max_episode_steps = exp_results_of_experiment_of_interest.problem_online_unrestricted.max_episode_steps + exp_results_of_experiment_of_interest.malfunction.malfunction_duration
```

# Inspect Solutions


## Solutions Gantt Charts of Agents Runnin

```{python}
for scope in all_scopes:
    df = [
        dict(Task=str(agent_id), Start=str(sorted_resource_occupations_per_agent[0].interval.from_incl), Finish=str(sorted_resource_occupations_per_agent[-1].interval.to_excl))
        for agent_id, sorted_resource_occupations_per_agent in sorted_resource_occupations_per_scope_and_agent[scope].items()
    ]

    fig = ff.create_gantt(df, title=f"Agents running in {scope}")
    fig.add_trace(
        go.Scatter(
            x = [malfunction.time_step, malfunction.time_step],
            y = [0, num_agents],
            mode = "lines",
            line = go.scatter.Line(color = "gray", width = 1),
            showlegend = False
        )
    )
    fig.add_trace(
        go.Scatter(
            x = [malfunction.time_step + malfunction.malfunction_duration, malfunction.time_step + malfunction.malfunction_duration],
            y = [0, num_agents],
            mode = "lines",
            line = go.scatter.Line(color = "gray", width = 1, dash="dot"),
            showlegend = False
        )
    )
    fig.update_xaxes(type='linear')
    fig.show()
```

## Solutions Time-Resource Graphs


The figure below shows the initial schedule we use as input to our re-scheduling pipeline. It is taken as given as used as target for optimization (minimal delay to initial schedule)

```{python}
all_agents_with_malfunction_agent_first=[malfunction.agent_id]+[agent_id for agent_id in range(num_agents) if agent_id != malfunction.agent_id]
```

```{python}
time_resource_graph_from_df(full_df=full_df, scopes=["schedule"], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

```{python}
time_resource_graph_from_df(full_df=full_df, scopes=["online_unrestricted"], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

```{python}
time_resource_graph_from_df(full_df=full_df, scopes=["online_unrestricted"], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

```{python}
time_resource_graph_from_df(full_df=full_df, scopes=["online_unrestricted"], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

```{python}
time_resource_graph_from_df(full_df=full_df, scopes=["offline_delta_weak"], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

```{python}
time_resource_graph_from_df(full_df=full_df, scopes=["online_route_restricted"], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

```{python}
time_resource_graph_from_df(full_df=full_df, scopes=["online_transmission_chains_fully_restricted"], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

```{python}
time_resource_graph_from_df(full_df=full_df, scopes=["online_transmission_chains_route_restricted"], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

```{python}
random_scopes = [scope for scope in all_scopes if "random" in scope]
for scope in random_scopes:
    time_resource_graph_from_df(full_df=full_df, scopes=[scope], time_step_interval=[0,max_episode_steps], num_agents=num_agents, agents_of_interest=all_agents_with_malfunction_agent_first, malfunction=malfunction)
```

### Solutions Changed Agents with Respect to Initial Schedule

```{python}
schedule_trainruns_dict = exp_results_of_experiment_of_interest.results_schedule.trainruns_dict
for scope in rescheduling_scopes:
    reschedule_trainruns_dict = exp_results_of_experiment_of_interest._asdict()[f"results_{scope}"].trainruns_dict
    values = [
        agent_id
        for agent_id, trainrun_reschedule in reschedule_trainruns_dict.items()
        if set(schedule_trainruns_dict[agent_id]) != set(trainrun_reschedule)
    ]
    print(f"{scope}: {values}")
```

```{python}
plot_changed_agents(exp_results_of_experiment_of_interest)
```

# Inspect Problems


## Problems Routing Alternatives, Speed and Time Windows

```{python}
print_path_stats(experiment_results=exp_results_of_experiment_of_interest)
plot_nb_route_alternatives(experiment_results=exp_results_of_experiment_of_interest)
```

```{python}
plot_agent_speeds(experiment_results=exp_results_of_experiment_of_interest)
```

```{python}
plot_time_window_sizes(experiment_results=exp_results_of_experiment_of_interest)
```

## Problems Time-Resource graphs
This visualization shows the parameter spaced available to the optimizer to find solutions. Initial schedule is not shown as we have a tabularasa approach with no restrictions.
Full rescheduling has the following available parameter space
Using the perfect oracle we can reduce the available parameters to disjunct patches in the space-time-continuum ;)

```{python}
# TODO replace with df-based ploggint, remove plotting_information stuff
plot_time_windows_all_scopes(experiment_results=exp_results_of_experiment_of_interest, plotting_information=plotting_information)
```

## Problems Heatmaps

```{python}
# TODO replace with df-based ploggint, remove plotting_information stuff
plot_shared_heatmap(plotting_information=plotting_information,experiment_result=exp_results_of_experiment_of_interest)
```

## Some metrics about the schedule


Number of active agents at each time step for the initial schedule

```{python}
plot_time_density(schedule_as_resource_occupations=resource_occupations_for_all_scopes.schedule)
```

Below we plot the resource occupation for the schedule and the difference between to the re-schedule as well as an indication of where agents start and where they travel. THe circles represent number of agents that either start or end at the city location.

```{python}
# TODO remove plotting_information stuff
plot_resource_occupation_heat_map(
    schedule_as_resource_occupations=resource_occupations_for_all_scopes.schedule,
    reschedule_as_resource_occupations=resource_occupations_for_all_scopes.offline_delta,
    plotting_information=plotting_information,
    title_suffix='Schedule'
)
```

Detailed paths of single trains

```{python}
plot_train_paths(
        schedule_as_resource_occupations=resource_occupations_for_all_scopes.schedule,
    plotting_information=plotting_information,
        agent_ids= [agent_of_interest])
```

## Solutions Costs

```{python}
plot_costs(experiment_results_analysis= exp_results_analysis_of_experiment_of_interest, height=1000)
```

## Solutions: Find Intervals and Agents with Changes in two Scopes

```{python}
change_range_dict = {}
left_scope = "online_unrestricted"
right_scope = "online_route_restricted"
for agent_id in range(num_agents):
    left_scope_ros = set(sorted_resource_occupations_per_scope_and_agent[left_scope][agent_id])
    right_scope_ros = set(sorted_resource_occupations_per_scope_and_agent[right_scope][agent_id])
    sym_diff = left_scope_ros.symmetric_difference(right_scope_ros)

    costs_from_route_section_penalties_left = exp_results_analysis_of_experiment_of_interest._asdict()[f"costs_from_route_section_penalties_per_agent_{left_scope}"][agent_id]
    costs_from_route_section_penalties_right = exp_results_analysis_of_experiment_of_interest._asdict()[f"costs_from_route_section_penalties_per_agent_{right_scope}"][agent_id]
    lateness_left = exp_results_analysis_of_experiment_of_interest._asdict()[f"lateness_per_agent_{left_scope}"][agent_id]
    lateness_right = exp_results_analysis_of_experiment_of_interest._asdict()[f"lateness_per_agent_{right_scope}"][agent_id]

    if (costs_from_route_section_penalties_left != costs_from_route_section_penalties_right) or (lateness_left != lateness_right):
        print(f"agent {agent_id} has costs differences       {left_scope}-{right_scope}")
        print(f"  lateness                           {lateness_left} - {lateness_right}")
        print(f"  costs_from_route_section_penalties {costs_from_route_section_penalties_left} - {costs_from_route_section_penalties_right}")

    if sym_diff:
        change_range_dict[agent_id]=(np.min([ro.interval.from_incl for ro in sym_diff]), np.max([ro.interval.to_excl for ro in sym_diff]))
        print(f"agent {agent_id} has changes in range between {left_scope} and {right_scope} in range {change_range_dict[agent_id]}")
print(change_range_dict)
change_range_lbs, change_range_ubs = list(zip(*change_range_dict.values()))

change_interval = (np.min(change_range_lbs), np.max(change_range_ubs))
print(change_interval)

df = [
    dict(Task=str(agent_id), Start=str(lb), Finish=str(ub))
    for agent_id, (lb,ub) in change_range_dict.items()
]

fig = ff.create_gantt(df, title=f"Intervals of changes between {left_scope} and {right_scope}")
fig.add_trace(
    go.Scatter(
        x = [malfunction.time_step, malfunction.time_step],
        y = [0, num_agents],
        mode = "lines",
        line = go.scatter.Line(color = "gray", width = 1),
        showlegend = False
    )
)
fig.add_trace(
    go.Scatter(
        x = [malfunction.time_step + malfunction.malfunction_duration, malfunction.time_step + malfunction.malfunction_duration],
        y = [0, num_agents],
        mode = "lines",
        line = go.scatter.Line(color = "gray", width = 1, dash="dot"),
        showlegend = False
    )
)
fig.update_xaxes(type='linear')
fig.show()
```

## Problems Visualization Subset of Agents and Time Range

```{python}
agents_of_interest = [20, 40, 31,18]
time_steps_interval_of_interest = [900,1720]
scopes_of_interest = ["online_unrestricted", "online_route_restricted"]
```

```{python}
scopes_of_interest = ["online_route_restricted"]
scatter_with_slider(full_df=full_df,
                    scopes=scopes_of_interest,
                    agents_of_interest=agents_of_interest,
                    time_step_interval=time_steps_interval_of_interest,
                    num_agents=num_agents,
                    x_dim="column", y_dim="row",
                    slider_dim="time_step",
                    range_x=[0,width], range_y=[height,0],
                    range_slider=change_interval,
                    df_background = df_background
                   )
```

```{python}
scopes_of_interest = ["online_unrestricted"]
time_resource_graph_from_df(full_df=full_df, scopes=scopes_of_interest, time_step_interval=time_steps_interval_of_interest, num_agents=num_agents, agents_of_interest=agents_of_interest, malfunction=malfunction, symbol="triangle-down")
```

```{python}
scopes_of_interest = ["online_route_restricted"]
time_resource_graph_from_df(full_df=full_df, scopes=scopes_of_interest, time_step_interval=time_steps_interval_of_interest, num_agents=num_agents, agents_of_interest=agents_of_interest, malfunction=malfunction, symbol="triangle-down")
```

```{python}
time_resource_graph_3d_from_df(full_df=full_df, scopes=scopes_of_interest, time_step_interval=time_steps_interval_of_interest, num_agents = num_agents, grid_width = width, grid_height = height, agents_of_interest=agents_of_interest)
```

## Problems Route DAGs

```{python}
# %matplotlib inline
plot_route_dag(exp_results_of_experiment_of_interest,agent_of_interest, ScheduleProblemEnum.PROBLEM_SCHEDULE)
```

```{python}
# %matplotlib inline
plot_route_dag(exp_results_of_experiment_of_interest,agent_of_interest, ScheduleProblemEnum.PROBLEM_RSP_FULL_AFTER_MALFUNCTION)
```

```{python}
# %matplotlib inline
plot_route_dag(exp_results_of_experiment_of_interest,agent_of_interest, ScheduleProblemEnum.PROBLEM_RSP_DELTA_PERFECT_AFTER_MALFUNCTION)
```

## Problems Solver Statistics

```{python}
for scope in all_scopes:
    results_scope = exp_results_of_experiment_of_interest._asdict()[f"results_{scope}"]
    print("=================================================================================")
    print("=================================================================================")
    print(f"= {scope} =")
    print("=================================================================================")
    print("=================================================================================")
    _print_stats(results_scope.solver_statistics)
    print("\n\n\n\n")

```
