---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
# %autosave 0
# %matplotlib notebook
# %matplotlib qt4
# %load_ext autoreload
# %autoreload 2
import sys
sys.path.append("../../src/python")
sys.path.append("../../src/asp")
import pandas as pd
from IPython.display import Video

from rsp.step_03_run.experiments import *
from rsp.step_03_run.experiment_results_analysis import *
from rsp.step_04_analysis.plot_utils import *
from rsp.step_04_analysis.compute_time_analysis.compute_time_analysis import *
from rsp.step_04_analysis.compute_time_analysis.asp_plausi import *
from rsp.utils.global_data_configuration import *
BASELINE_DATA_FOLDER = f"../../{BASELINE_DATA_FOLDER}"


from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))
from_cache = False
from_individual_csv = True
```

```{python}
# Filter data depending on full rescheduling time (>=20s and <= 200s)
local_filter_experiment_results_analysis_data_frame = partial(
    filter_experiment_results_analysis_data_frame,
    min_time_online_unrestricted=0,
    max_time_online_unrestricted=200,
    max_time_online_unrestricted_q=1.0
)
experiments_of_interest = None
baseline_data_folder = BASELINE_DATA_FOLDER

experiment_data_baseline = load_and_filter_experiment_results_analysis(
    experiments_of_interest = experiments_of_interest,
    experiment_base_directory = baseline_data_folder,
    local_filter_experiment_results_analysis_data_frame=local_filter_experiment_results_analysis_data_frame
)

experiment_data_comparison_seq = load_and_filter_experiment_results(
    experiments_of_interest = experiments_of_interest,
    experiment_base_directory = baseline_data_folder.replace("baseline", "with_seq"),
    #local_filter_experiment_results_analysis_data_frame=local_filter_experiment_results_analysis_data_frame,
    local_filter_experiment_results_analysis_data_frame=None,
    online_unrestricted_only=True
)



display(experiment_data_baseline)
display(experiment_data_comparison_seq)
```

# Visualize Compuational time comparison


# Visualize effect of SEQ heuristics (SIM-167)


### Discussion effect sequence heuristic
The sequence heuristic seems not to have a consistent positive effect on run times. Do we understand why?

```{python}
display(experiment_data_comparison_seq["experiment_parameters"].map(lambda p: eval(p).experiment_id))
hypothesis_one_analysis_visualize_computational_time_comparison(
    experiment_data=experiment_data_baseline,
    experiment_data_comparison=experiment_data_comparison_seq,
)
```

# Visualize effect of delay model resolution (SIM-542)


## delay resolution 1 -> 2

```{python}
from rsp.step_04_analysis.detailed_experiment_analysis import hypothesis_one_analysis_visualize_computational_time_comparison
agenda_name_comparison_delay_2 = '003_a_bit_more_advanced_schedules_only_2020_06_19T16_23_16_with_delay_model_resolution_2_2020_07_16T06_37_21'
experiment_base_directory_comparison_delay_2 = f'../rsp-data/{agenda_name_comparison_delay_2}'
experiment_data_directory_comparison_delay_2 = f'{experiment_base_directory_comparison_delay_2}/{EXPERIMENT_DATA_SUBDIRECTORY_NAME}'

experiment_results_list_comparison_delay_2 = load_and_expand_experiment_results_from_data_folder(
    experiment_data_folder_name=experiment_data_directory_comparison_delay_2,
    nonify_all_structured_fields=True
)
experiment_data_comparison_delay_2: pd.DataFrame = convert_list_of_experiment_results_analysis_to_data_frame(experiment_results_list_comparison_delay_2)


```

### Discussion effect of delay model resolution 1->2
Delay model resolution seems to have a considerable speed-up

```{python}
hypothesis_one_analysis_visualize_computational_time_comparison(
    experiment_data_baseline=experiment_data_baseline,
    experiment_data=experiment_data_comparison_delay_2,
    experiment_data_baseline_suffix=f'_{agenda_name_baseline}',
    experiment_data_suffix=f'_{agenda_name_comparison_delay_2}'
)
```

## delay resolution 1 -> 5

```{python}
from rsp.step_04_analysis.detailed_experiment_analysis import hypothesis_one_analysis_visualize_computational_time_comparison
agenda_name_comparison_delay_5 = '003_a_bit_more_advanced_schedules_only_2020_06_19T16_23_16_with_delay_model_resolution_5_2020_07_16T07_52_55'
experiment_base_directory_comparison_delay_5 = f'../rsp-data/{agenda_name_comparison_delay_5}'
experiment_data_directory_comparison_delay_5 = f'{experiment_base_directory_comparison_delay_5}/{EXPERIMENT_DATA_SUBDIRECTORY_NAME}'

experiment_results_list_comparison_delay_5 = load_and_expand_experiment_results_from_data_folder(
    experiment_data_folder_name=experiment_data_directory_comparison_delay_5,
    nonify_all_structured_fields=True
)
experiment_data_comparison_delay_5: pd.DataFrame = convert_list_of_experiment_results_analysis_to_data_frame(experiment_results_list_comparison_delay_5)


```

### Discussion effect of delay model resolution 1->5
The effect is even positively stronger than with 2.

```{python}
hypothesis_one_analysis_visualize_computational_time_comparison(
    experiment_data_baseline=experiment_data_baseline,
    experiment_data=experiment_data_comparison_delay_5,
    experiment_data_baseline_suffix=f'_{agenda_name_baseline}',
    experiment_data_suffix=f'_{agenda_name_comparison_delay_5}'
)
```

## delay resolution 1 -> 10

```{python}
from rsp.step_04_analysis.detailed_experiment_analysis import hypothesis_one_analysis_visualize_computational_time_comparison
agenda_name_comparison_delay_10 = '003_a_bit_more_advanced_schedules_only_2020_06_19T16_23_16_with_delay_model_resolution_10_2020_07_16T08_33_50'
experiment_base_directory_comparison_delay_10 = f'../rsp-data/{agenda_name_comparison_delay_10}'
experiment_data_directory_comparison_delay_10 = f'{experiment_base_directory_comparison_delay_10}/{EXPERIMENT_DATA_SUBDIRECTORY_NAME}'

experiment_results_list_comparison_delay_10 = load_and_expand_experiment_results_from_data_folder(
    experiment_data_folder_name=experiment_data_directory_comparison_delay_10,
    nonify_all_structured_fields=True
)
experiment_data_comparison_delay_10: pd.DataFrame = convert_list_of_experiment_results_analysis_to_data_frame(experiment_results_list_comparison_delay_10)

```

### Discussion effect of delay model resolution 1->10

```{python}
hypothesis_one_analysis_visualize_computational_time_comparison(
    experiment_data_baseline=experiment_data_baseline,
    experiment_data=experiment_data_comparison_delay_10,
    experiment_data_baseline_suffix=f'_{agenda_name_baseline}',
    experiment_data_suffix=f'_{agenda_name_comparison_delay_10}'
)
```

# Visualize effect of --propagate (SIM-543)

```{python}
from rsp.step_04_analysis.detailed_experiment_analysis import hypothesis_one_analysis_visualize_computational_time_comparison
agenda_name_comparison_without_propagate = '003_a_bit_more_advanced_schedules_only_2020_06_19T16_23_16_without_propagate_partial_2020_07_16T09_10_03'
experiment_base_directory_comparison_without_propagate = f'../rsp-data/{agenda_name_comparison_without_propagate}'
experiment_data_directory_comparison_without_propagate = f'{experiment_base_directory_comparison_without_propagate}/{EXPERIMENT_DATA_SUBDIRECTORY_NAME}'

experiment_results_list_comparison_without_propagate = load_and_expand_experiment_results_from_data_folder(
    experiment_data_folder_name=experiment_data_directory_comparison_without_propagate,
    nonify_all_structured_fields=True
)
experiment_data_comparison_without_propagate: pd.DataFrame = convert_list_of_experiment_results_analysis_to_data_frame(experiment_results_list_comparison_without_propagate)
```

### Discussion without --propagate
No consistent effect of disabling propagation.

```{python}
hypothesis_one_analysis_visualize_computational_time_comparison(
    experiment_data_baseline=experiment_data_baseline,
    experiment_data=experiment_data_comparison_without_propagate,
    experiment_data_baseline_suffix=f'_{agenda_name_baseline}',
    experiment_data_suffix=f'_{agenda_name_comparison_without_propagate}'
)
```

# Visualize effect of different time window sizes (TODO)

```{python}

```

# Visualize effect of different ASP solver seeds (TODO)

```{python}

```
