INFRAS_AND_SCHEDULES_FOLDER = "../rsp-data/ONE_INFRA_MANY_SCHEDULES_64_AGENTS/"
BASELINE_DATA_FOLDER = "../rsp-data/ONE_INFRA_MANY_SCHEDULES_64_AGENTS/ONE_INFRA_MANY_SCHEDULES_64_AGENTS_baseline_2020_10_23T07_30_03/"
