# CAVEAT: no final slash! (basename of path with final slash is empty)
INFRAS_AND_SCHEDULES_FOLDER = "../rsp-data/PUBLICATION_DATA_LARGE/"
BASELINE_DATA_FOLDER = "../rsp-data/PUBLICATION_DATA/PUBLICATION_DATA_baseline_2020_11_17T23_40_54/"
BASELINE_DATA_FOLDER = "../rsp-data/PUBLICATION_DATA/NEW_RUN/"
