# CAVEAT: no final slash! (basename of path with final slash is empty)
INFRAS_AND_SCHEDULES_FOLDER = "DENSITY_VARIATION_EXPERIMENTS_FIXED"
BASELINE_DATA_FOLDER = "DENSITY_VARIATION_EXPERIMENTS_FIXED/DENSITY_VARIATION_EXPERIMENTS_FIXED_baseline_2020_11_05T09_58_04"
